name: repaso
description: "A new Flutter project."

publish_to: 'none'
version: 2.12.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  app_tracking_transparency: ^2.0.6+1
  buttons_tabbar: ^1.3.15
  custom_refresh_indicator: ^4.0.1
  cloud_firestore: ^5.5.1
  cloud_functions: ^5.4.0
  crypto: ^3.0.6
  csv: ^5.0.0
  cupertino_icons: ^1.0.8
  excel: ^4.0.6
  file_picker: ^8.1.4
  firebase_analytics: ^11.4.5
  firebase_auth: ^5.3.2
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.4
  fl_chart: ^0.69.2
  flutter_gemini: ^3.0.0
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.2
  flutter_markdown: ^0.7.7+1
  font_awesome_flutter: ^10.8.0
  google_mobile_ads: ^6.0.0
  google_mlkit_text_recognition: ^0.15.0
  google_sign_in: ^6.2.2
  http: ^1.3.0
  image: ^4.3.0
  in_app_review: ^2.0.10
  image_cropper: ^8.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  material_symbols_icons: ^4.2815.1
  package_info_plus: ^8.2.0
  path_drawing: ^1.0.1
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  share_plus: ^10.1.2
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^6.1.4
  sliding_sheet2: ^2.0.1
  flutter_sticky_header: ^0.8.0
  syncfusion_flutter_charts: ^28.1.33
  url_launcher: ^6.3.1
  version: ^3.0.2
  purchases_flutter: ^8.8.1


flutter_native_splash:
  # ロード画面の背景色
  color: "#1E5CFF"
  # 表示する画像。assets/new_logo.png が対象です。
  image: assets/splash/splash.v3.png
  # 対象プラットフォーム（不要なプラットフォームは false にしてください）
  android: true
  android_gravity: center
  ios: true
  ios_content_mode: center
  # webやその他のプラットフォームが不要ならfalseにできます
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/Icons.school.v3.png"

flutter:
  uses-material-design: true
  assets:
    - assets/paywall/paywall.png
    - assets/google/ios_neutral_rd_na@3x.png
    - assets/default_profile_icon/default_profile_icon_v1.0.png
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700



