// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk9F_HrQEIsGmrzRJwfwL8etBBwJS8OyI',
    appId: '1:967790239352:web:ae709ae6e4dd88fc8fd78d',
    messagingSenderId: '967790239352',
    projectId: 'repaso-rbaqy4',
    authDomain: 'repaso-rbaqy4.firebaseapp.com',
    storageBucket: 'repaso-rbaqy4.appspot.com',
    measurementId: 'G-QQRG3T2GMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB4R3rv97-zOeMcdhzgWtT_L3mJ-iczuo',
    appId: '1:967790239352:android:1a275d083f0224f88fd78d',
    messagingSenderId: '967790239352',
    projectId: 'repaso-rbaqy4',
    storageBucket: 'repaso-rbaqy4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv-azpPvjkBE7cIJcWsiLJVjFKwmtqZEM',
    appId: '1:967790239352:ios:a17fea1966095fdc8fd78d',
    messagingSenderId: '967790239352',
    projectId: 'repaso-rbaqy4',
    storageBucket: 'repaso-rbaqy4.appspot.com',
    androidClientId: '967790239352-rail73qn41g8po7d2bq56mb4u4jtm4fr.apps.googleusercontent.com',
    iosClientId: '967790239352-0kdq2n0d7ln631dscch8bu9899qioqlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.repaso',
  );
}
